# Generated by Django 5.1.6 on 2025-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("citizen_dashboard", "0005_urgentcaselist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UrgentCaseList",
        ),
    ]
